mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
	path('', include('polls.urls')),
	#path('Host/', include('polls.urls')),
    #path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

#if settings.DEBUG:
#    urlpatterns= urlpatterns + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
#    urlpatterns= urlpatterns + static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

mysite/polls/urls.py
from django.urls import path
#from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    path('Taxonomy/', views.TaxonomyView.as_view(), name='Taxonomy'),
    path('Host/', views.HostView.as_view(), name='Host'),
    path('Protein/', views.ProteinView.as_view(), name='Protein'),
    path('Peptide/', views.PeptideView.as_view(), name='Peptide'),
    path('Structure/', views.StructureView.as_view(), name='Structure'),
    path('PeptideStructure/', views.PeptideStructureView.as_view(), name='PeptideStructure'),
    path('References/', views.ReferencesView.as_view(), name='References'),
    

    #path('HostTable/', views.HostTable, name='HostTable'),


    path('HostSearch/', views.HostSearchView, name='HostSearch'),
    path('TaxonomySearch/', views.TaxonomySearchView, name='TaxonomySearch'),
    path('ProteinSearch/', views.ProteinSearchView, name='ProteinSearch'),
    path('PeptideSearch/', views.PeptideSearchView, name='PeptideSearch'),
    path('StructureSearch/', views.StructureSearchView, name='StructureSearch'),
    #path('PeptideStructure/', views.PeptideStructureView.as_view(), name='PeptideStructure'),
    path('ReferencesSearch/', views.ReferencesSearchView, name='ReferencesSearch'),


    path('HostAdd/', views.addHost, name='HostAdd'),
    path('TaxonomyAdd/', views.addTaxonomy, name='TaxonomyAdd'),


    #path('', Host.IndexView.as_view(), name='index'),
    #path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    #path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    #path('<int:question_id>/vote/', views.vote, name='vote'),
    #path('', views.Host.as_view(), name='Host'),
]

mysite/polls/views.py
import operator

from django.utils import timezone

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.db.models import Q



from .models import *


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        #Return the last five published questions.
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    ... # same as above, no changes needed.
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


class HostView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        
        return Host.objects.all()

"""
def searchHost(request):
    query = request.GET.get('q')
    try:
        query = int(query)
    except ValueError:
        query = None
        results = None
    if query:
        results = Host.objects.get(idhost=query)
    context = RequestContext(request)
    return render_to_response('results.html', {"results": results,}, context_instance=context)
    """

class TaxonomyView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        
        return TaxanomyVirus.objects.all()


class ProteinView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        
        return Protein.objects.all()


class PeptideView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        
        return FusionPeptides.objects.all()


class StructureView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        
        return Structure.objects.all()

class PeptideStructureView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        
        return PeptideStructure.objects.all()


class ReferencesView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        
        return References.objects.all()


"""
###############

def HostTable(request):
    return render(request, 'polls/tableHost.html', {'Host': Host.objects.all()})


########################
"""

def HostSearchView(request):
    if request.method == 'GET':
        query= request.GET.get('q')

        submitbutton= request.GET.get('submit')

        if query is not None:
            lookups= Q(idhost__icontains=query) | Q(host__icontains=query)

            results= Host.objects.filter(lookups).distinct()

            context={'results': results,
                     'submitbutton': submitbutton}

            return render(request, 'polls/search_host.html', context)

        else:
            return render(request, 'polls/search_host.html')

    else:
        return render(request, 'polls/search_host.html')


def TaxonomySearchView(request):
    if request.method == 'GET':
        query= request.GET.get('q')

        submitbutton= request.GET.get('submit')

        if query is not None:
            lookups= Q(idtaxanomy__icontains=query) | Q(commonname__icontains=query) | Q(family__icontains=query) |  Q(genre__icontains=query) |  Q(species__icontains=query) | Q(subspecies__icontains=query) | Q(ncbitax__icontains=query)

            results= TaxanomyVirus.objects.filter(lookups).distinct()

            context={'results': results,
                     'submitbutton': submitbutton}

            return render(request, 'polls/search_tax.html', context)

        else:
            return render(request, 'polls/search_tax.html')

    else:
        return render(request, 'polls/search_tax.html')


def ProteinSearchView(request):
    if request.method == 'GET':
        query= request.GET.get('q')

        submitbutton= request.GET.get('submit')

        if query is not None:
            lookups= Q(idprotein__icontains=query) | Q(name__icontains=query) | Q(class_field__icontains=query) |  Q(activation__icontains=query) |  Q(name_fusogenic_unit__icontains=query) | Q(location_fusogenic__icontains=query) | Q(sequence_fusogenic__icontains=query) | Q(uniprotid__icontains=query) | Q(ncbiid__icontains=query) | Q(ncbiid__icontains=query)

            results= Protein.objects.filter(lookups).distinct()

            context={'results': results,
                     'submitbutton': submitbutton}

            return render(request, 'polls/search_protein.html', context)

        else:
            return render(request, 'polls/search_protein.html')

    else:
        return render(request, 'polls/search_protein.html')


def PeptideSearchView(request):
    if request.method == 'GET':
        query= request.GET.get('q')

        submitbutton= request.GET.get('submit')

        if query is not None:
            lookups= Q(idfusion_peptides__icontains=query) | Q(residues__icontains=query) | Q(sequence__icontains=query) |  Q(annotation_method__icontains=query) |  Q(exp_evidence__icontains=query) 

            results= FusionPeptides.objects.filter(lookups).distinct()

            context={'results': results,
                     'submitbutton': submitbutton}

            return render(request, 'polls/search_peptide.html', context)

        else:
            return render(request, 'polls/search_peptide.html')

    else:
        return render(request, 'polls/search_peptide.html')


def StructureSearchView(request):
    if request.method == 'GET':
        query= request.GET.get('q')

        submitbutton= request.GET.get('submit')

        if query is not None:
            lookups= Q(idstructure__icontains=query) | Q(exp_method__icontains=query) | Q(repository__icontains=query) 

            results= Structure.objects.filter(lookups).distinct()

            context={'results': results,
                     'submitbutton': submitbutton}

            return render(request, 'polls/search_structure.html', context)

        else:
            return render(request, 'polls/search_structure.html')

    else:
        return render(request, 'polls/search_structure.html')


#falta PeptideStructureView

def ReferencesSearchView(request):
    if request.method == 'GET':
        query= request.GET.get('q')

        submitbutton= request.GET.get('submit')

        if query is not None:
            lookups= Q(idreferences__icontains=query) | Q(type_reference__icontains=query) | Q(doi__icontains=query) 

            results= References.objects.filter(lookups).distinct()

            context={'results': results,
                     'submitbutton': submitbutton}

            return render(request, 'polls/search_ref.html', context)

        else:
            return render(request, 'polls/search_ref.html')

    else:
        return render(request, 'polls/search_ref.html')




############################################


def addHost(request):
    if request.method == 'POST':
        if request.POST.get('host'):
            
            new_host=Host()

            max_id = Host.objects.all().order_by("-idhost")[0]
        

            #new_host.idhost= request.POST.get('idHost')
            new_host.idhost = int(max_id.idhost) + 1
            
            new_host.host= request.POST.get('host')
            new_host.save()
                
            return render(request, 'polls/add_host.html')  

    else:
        return render(request,'polls/add_host.html')


def addTaxonomy(request):
    if request.method == 'POST':
        if request.POST.get('commonname'):
            
            new_tax=TaxanomyVirus()

            max_id = TaxanomyVirus.objects.all().order_by("-idtaxanomy")[0]
        
            new_tax.idtaxanomy = int(max_id.idtaxanomy) + 1
            
            new_tax.commonname= request.POST.get('commonname')
            
            if request.POST.get('family'): new_tax.family= request.POST.get('family')
            else: new_tax.family= None

            if request.POST.get('genre'): new_tax.genre= request.POST.get('genre')
            else: new_tax.genre= None

            if request.POST.get('species'): new_tax.species= request.POST.get('species')
            else: new_tax.species= None

            if request.POST.get('subspecies'): new_tax.subspecies= request.POST.get('subspecies')
            else: new_tax.subspecies= None

            if request.POST.get('ncbitax'): new_tax.ncbitax= request.POST.get('ncbitax')
            else: new_tax.ncbitax= None

mysite/polls/templates/polls/add_host.html
<html>
<head>
<title>Add Host </title>
</head>

<body>
<h1>Add Host </h1>
<form action="" method="POST">
{% csrf_token %}
Host: <input type="text" name="host"/><br/>
<!--
Content: <br/>
<textarea cols="35" rows="8" name="new_host">
</textarea><br/>
-->
<input type="submit" value="Post"/>
</form>
</body>

</html>

mysite/polls/templates/polls/add_tax.html
<html>
<head>
<title>Add Taxonomy </title>
</head>

<body>
<h1>Add Taxonomy </h1>
<form action="" method="POST">
{% csrf_token %}
commonname: <input type="text" name="commonname"/><br/>
family: <input type="text" name="family"/><br/>
genre: <input type="text" name="genre"/><br/>
species: <input type="text" name="species"/><br/>
subspecies: <input type="text" name="subspecies"/><br/>
ncbitax: <input type="text" name="ncbitax"/><br/>
<!--
Content: <br/>
<textarea cols="35" rows="8" name="new_host">
</textarea><br/>
-->
<input type="submit" value="Post"/>
</form>
</body>

</html>

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

mysite/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    
    <ul>
    {% for question in latest_question_list %}
        <p>{{ question }}</p></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/polls/templates/polls/index_get.html
<form method="GET" action="" id="searchform">
    <input class="searchfield" id="searchbox" name="q" type="text" value="{{ request.GET.q }}" placeholder="Search..."/>
</form>

mysite/polls/templates/polls/index_host.html
{# tutorial/templates/tutorial/people.html #}
{% load render_table from django_tables2 %}
<!doctype html>
<html>
    <head>
        <title>List of Host</title>
    </head>
    <body>
        {% render_table HostView %}
    </body>
</html>

mysite/polls/templates/polls/list.html
{# yonetim/templates/list.html #}
{% load render_table from django_tables2 %}
{% load static %}
<!doctype html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 
'ticket/static/css/screen.css' %}" />
    </head>
    <body>
        {% render_table latest_question_list %}
    </body>
</html>

mysite/polls/templates/polls/search.html
<form method="get" action="/search/">
  Search Notecards:<input type="text" name="q" id="id_q" value="{{ query }}"/>
  <input type="submit" value="Search" />
</form>

mysite/polls/templates/polls/search_host.html
<h1>Search Host</h1>

<br/>
<form action="{% url 'polls:HostSearch' %}" method="GET" value="{{request.GET.q}}">
Search <input type="text" name="q" value="{{request.GET.q}}" placeholder="Search posts"/>
<input type="submit" name="submit" value="Search"/>
</form>


{% if submitbutton == 'Search' and request.GET.q != '' %}
{% if results %}
<h1>Results for <b>{{ request.GET.q }}</b></h1>
<br/><br/>

{% for result in results %}

{{result}}
<br/>

{% endfor %}
{% else %}
No search results for this query
{% endif %}
{% endif %}

mysite/polls/templates/polls/search_peptide.html
<h1>Search Fusion Peptide</h1>

<br/>
<form action="{% url 'polls:PeptideSearch' %}" method="GET" value="{{request.GET.q}}">
Search <input type="text" name="q" value="{{request.GET.q}}" placeholder="Search posts"/>
<input type="submit" name="submit" value="Search"/>
</form>


{% if submitbutton == 'Search' and request.GET.q != '' %}
{% if results %}
<h1>Results for <b>{{ request.GET.q }}</b></h1>
<br/><br/>

{% for result in results %}

{{result}}
<br/>

{% endfor %}
{% else %}
No search results for this query
{% endif %}
{% endif %}

mysite/polls/templates/polls/search_protein.html
<h1>Search Protein</h1>

<br/>
<form action="{% url 'polls:ProteinSearch' %}" method="GET" value="{{request.GET.q}}">
Search <input type="text" name="q" value="{{request.GET.q}}" placeholder="Search posts"/>
<input type="submit" name="submit" value="Search"/>
</form>


{% if submitbutton == 'Search' and request.GET.q != '' %}
{% if results %}
<h1>Results for <b>{{ request.GET.q }}</b></h1>
<br/><br/>

{% for result in results %}

{{result}}
<br/>

{% endfor %}
{% else %}
No search results for this query
{% endif %}
{% endif %}

mysite/polls/templates/polls/search_ref.html
<h1>Search References</h1>

<br/>
<form action="{% url 'polls:ReferencesSearch' %}" method="GET" value="{{request.GET.q}}">
Search <input type="text" name="q" value="{{request.GET.q}}" placeholder="Search posts"/>
<input type="submit" name="submit" value="Search"/>
</form>


{% if submitbutton == 'Search' and request.GET.q != '' %}
{% if results %}
<h1>Results for <b>{{ request.GET.q }}</b></h1>
<br/><br/>

{% for result in results %}

{{result}}
<br/>

{% endfor %}
{% else %}
No search results for this query
{% endif %}
{% endif %}

mysite/polls/templates/polls/search_tax.html
<h1>Search Taxonomy</h1>

<br/>
<form action="{% url 'polls:TaxonomySearch' %}" method="GET" value="{{request.GET.q}}">
Search <input type="text" name="q" value="{{request.GET.q}}" placeholder="Search posts"/>
<input type="submit" name="submit" value="Search"/>
</form>


{% if submitbutton == 'Search' and request.GET.q != '' %}
{% if results %}
<h1>Results for <b>{{ request.GET.q }}</b></h1>
<br/><br/>

{% for result in results %}

{{result}}
<br/>

{% endfor %}
{% else %}
No search results for this query
{% endif %}
{% endif %}

mysite/polls/templates/polls/tableHost.html
{% load render_table from django_tables2 %}
<!doctype html>
<html>
    <head>
        <title>List of Host</title>
    </head>
    <body>
        {% render_table Host %}
    </body>
</html>